{% set prefix = cookiecutter.deploy_name %}
{% set num_splashes = cookiecutter.num_splashes|int %}
{% set max_timeout = cookiecutter.max_timeout|int %}
{% set maxrss = cookiecutter.maxrss_mb | int %}
{% set mem_limit = "%dm" | format(maxrss * 1.2) %}
{% set memswap_limit = "%dm" | format(maxrss * 1.5) %}

{{ prefix }}-haproxy:
    image: haproxy:1.5
    ports:
        # stats
        - "8036:8036"

        # splash
        - "8050:8050"
    links:
        {%- for i in range(num_splashes) %}
        - {{ prefix }}-splash{{i}}
        {%- endfor %}
    volumes:
        - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro


{{ prefix }}-splash0:
    image: scrapinghub/splash:{{ cookiecutter.splash_version }}
    command: --max-timeout {{ max_timeout }} --disable-proxy --slots 10 --maxrss {{ maxrss }}
    expose:
        - 8050
    mem_limit: {{ mem_limit }}
    memswap_limit: {{ memswap_limit }}
    restart: always

{%- for i in range(1, num_splashes) %}
{{ prefix }}-splash{{i}}:
    extends:
        service: {{ prefix }}-splash0
{%- endfor %}
