






version: '3'

services:
    haproxy:
        image: haproxy:1.7
        ports:
            # stats
            - "8036:8036"

            # splash
            - "8050:8050"
        depends_on:
            - splash0
            - splash1
            - splash2
        volumes:
            - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
        networks:
            splash_cluster_network: {}

    splash0:
        image: scrapinghub/splash:3.0
        deploy:
            resources:
                limits:
                    memory: 4200m
            restart_policy:
                condition: on-failure
                delay: 5s
        command: --max-timeout 3600 --slots 5 --maxrss 3000 --verbosity 1
        expose:
            - 8050
        volumes:
            - ./filters:/etc/splash/filters:ro
        networks:
            splash_cluster_network: {}

    splash1:
        image: scrapinghub/splash:3.0
        deploy:
            resources:
                limits:
                    memory: 4200m
            restart_policy:
                condition: on-failure
                delay: 5s
        command: --max-timeout 3600 --slots 5 --maxrss 3000 --verbosity 1
        expose:
            - 8050
        volumes:
            - ./filters:/etc/splash/filters:ro
        networks:
            splash_cluster_network: {}

    splash2:
        image: scrapinghub/splash:3.0
        deploy:
            resources:
                limits:
                    memory: 4200m
            restart_policy:
                condition: on-failure
                delay: 5s
        command: --max-timeout 3600 --slots 5 --maxrss 3000 --verbosity 1
        expose:
            - 8050
        volumes:
            - ./filters:/etc/splash/filters:ro
        networks:
            splash_cluster_network: {}

networks:
    splash_cluster_network:
        driver: bridge